### PR TITLE
Remove Walmyr Carvalho moderation mention

### PR DESCRIPTION
**Pull request by walmyrcarvalho**
The title speaks for itself. :)

### CODE REVIEW

**Review by marcelofabri — CHANGES_REQUESTED** [review]
🚫

**Comment by walmyrcarvalho** [comment]
@marcelofabri Care to elaborate?

**Review by barbosa — APPROVED** [review]
😢

**Comment by walmyrcarvalho** [comment]
Thanks, @barbosa and @marcelofabri! :)

**Pull request merged**
